version: '3.8'

services:
    dev:
        image: hyperschedule-dev-container
        build:
            dockerfile: dev-container.dockerfile
        depends_on:
            base:
                condition: service_completed_successfully
        init: true
        command: sleep 2147483647 # 2^31 - 1
        hostname: hyperschedule-dev-container
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - .:/srv/hyperschedule/
            - node_modules:/srv/hyperschedule/node_modules
