# Simple workflow for deploying static content to GitHub Pages
name: Generate API docs and post to GH-Pages

on:
  # Runs on pushes targeting the default branch
  workflow_run:
    workflows:
      - Run tests and lints
    types: [completed]
    branches: [v2]
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: MuddCreates/hyperschedule/.github/workflows/build.yaml@v2
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate doc in shared
        run: yarn --cwd shared doc
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'shared/api_docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
