name: Run tests and lints

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we use matrix so we can run those in parallel
        command: [test, lint, format-check]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install all dependencies
        run: yarn install --frozen-lockfile
      - name: Run ${{matrix.command}}
        run: yarn ${{matrix.command}}
