name: Run all automated checks

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "v2"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we use matrix so we can run those in parallel
        command: ["typecheck", "test", "lint", "format"]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run ${{matrix.command}}
        run: yarn ci:${{matrix.command}}
